// One-off generator: emit app/src/sheet/univer-icons.css that re-skins Univer's
// toolbar icons with lucide (the app's icon set). For each Univer icon (keyed on
// its stable `univerjs-icon-<name>-icon` SVG class) we hide the original glyph and
// paint the matching lucide SVG via CSS mask in currentColor. Exact lucide path
// data is read from node_modules/lucide-solid so nothing is hand-transcribed.
import { readFileSync, writeFileSync } from "node:fs";

// Univer icon name (from `univerjs-icon-<name>-icon`) -> lucide-solid icon file (kebab).
// Left intentionally un-mapped: font-color-double / paint-bucket-double (live color
// swatch), and niche ones with no clean lucide twin (align-bottom, no-rotation,
// add-digits, reduce-digits, shortcut, fx, increase, convert, hide-gridlines-double,
// reduce). "most of those", as asked.
const MAP: Record<string, string> = {
  undo: "undo",
  redo: "redo",
  brush: "paintbrush",
  "clear-format-double": "remove-formatting",
  "font-size-increase": "a-arrow-up",
  "font-size-reduce": "a-arrow-down",
  bold: "bold",
  italic: "italic",
  underline: "underline",
  strikethrough: "strikethrough",
  "all-border": "table",
  "left-justifying": "text-align-start",
  "merge-all": "combine",
  percent: "percent",
  dollar: "dollar-sign",
  protect: "lock",
  close: "x",
  "check-mark": "check",
  "more-down": "chevron-down",
  dropdown: "chevron-down",
  overflow: "text-wrap",
  "more-function": "ellipsis",
};

const ICON_DIR = "app/node_modules/lucide-solid/dist/esm/icons";

function lucideSvg(name: string): string | null {
  let src: string;
  try {
    src = readFileSync(`${ICON_DIR}/${name}.mjs`, "utf8");
  } catch {
    return null;
  }
  const m = src.match(/const iconNode = (\[[\s\S]*?\]);/);
  if (!m) return null;
  // iconNode is pure data: array of [tag, attrsObject]. Safe to eval from our own dep.
  const nodes = eval(m[1]) as [string, Record<string, string>][];
  const children = nodes
    .map(([tag, attrs]) => {
      const a = Object.entries(attrs)
        .filter(([k]) => k !== "key")
        .map(([k, v]) => `${k}="${v}"`)
        .join(" ");
      return `<${tag} ${a}/>`;
    })
    .join("");
  // stroke color is irrelevant for an alpha mask; currentColor paints it later.
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${children}</svg>`;
}

let css = `/* GENERATED by gen-univer-icons.ts — do not edit by hand.
   Re-skins Univer's toolbar icons with lucide (currentColor mask, keyed on Univer's
   stable univerjs-icon-*-icon classes; survives Univer re-renders). Regenerate with:
   bun gen-univer-icons.ts */\n\n`;
const missing: string[] = [];
for (const [univer, lucide] of Object.entries(MAP)) {
  const svg = lucideSvg(lucide);
  if (!svg) {
    missing.push(`${univer} -> ${lucide}`);
    continue;
  }
  const uri = `data:image/svg+xml,${encodeURIComponent(svg)}`;
  const sel = `.oa-sheet svg.univerjs-icon-${univer}-icon`;
  css +=
    `${sel}{-webkit-mask:url("${uri}") center/contain no-repeat;` +
    `mask:url("${uri}") center/contain no-repeat;background-color:currentColor!important}\n` +
    `${sel} > *{display:none!important}\n`;
}

writeFileSync("app/src/sheet/univer-icons.css", css);
console.log(`wrote app/src/sheet/univer-icons.css with ${Object.keys(MAP).length - missing.length} icons`);
if (missing.length) console.log("MISSING lucide icons:", missing.join(", "));
