// app/src/icons/iconNames.ts
//
// The 140 canonical icon names every icon set must resolve — the NAME seam registry.ts:3 refers
// to. This list is SET-INDEPENDENT: it does not change when the art behind a name does (Nerd Font
// -> Phosphor -> whatever comes next), which is what keeps the ~100 real call sites (FileTree,
// toolbar, palette, command catalog...) stable across a set swap. Only the MAPPING from these
// names to a set's own identifiers changes — see iconMap.ts for the current one.
//
// Deliberately its own module rather than reading a set's own identifiers at runtime: a live seam
// should not depend on any one set's internals, so this list is hand-maintained and each set
// (formerly the Nerd Font codepoint table, now iconMap.ts's Phosphor mapping) is checked against
// it instead of the other way round.
//
// Sourced from the retired Nerd Font era's codepoint table's key set at the time of the Phosphor
// migration (2026-08-27) — see .claude/plans/2026-08-27-visual-unification-audit.md §10. That
// table (icons/nerdGlyphs.ts) and its cross-check test were deleted (ds-conformance Task 8) once
// nothing referenced the font it described; this list is unaffected — it was already
// set-independent and needed no replacement source.
export const ICON_NAMES: string[] = [
    'AppWindow',
    'Archive',
    'ArchiveX',
    'ArrowDown',
    'ArrowLeft',
    'ArrowRight',
    'ArrowUp',
    'AtSign',
    'Ban',
    'Blend',
    'Bold',
    'Book',
    'BookOpen',
    'Bot',
    'Box',
    'Brain',
    'BrainCircuit',
    'Bug',
    'Calendar',
    'CalendarX',
    'CaseSensitive',
    'ChartColumn',
    'ChartLine',
    'Check',
    'ChevronDown',
    'ChevronLeft',
    'ChevronRight',
    'ChevronUp',
    'CircleCheck',
    'CircleHelp',
    'CircleX',
    'Clipboard',
    'ClipboardList',
    'Code',
    'Columns2',
    'Columns3',
    'Combine',
    'Copy',
    'Crown',
    'Database',
    'Download',
    'Eraser',
    'ExternalLink',
    'Eye',
    'File',
    'FilePlus',
    'FileText',
    'Flame',
    'Folder',
    'FolderInput',
    'FolderOpen',
    'FolderPlus',
    'Gauge',
    'Globe',
    'Grid3x3',
    'Hash',
    'Heading1',
    'Heading2',
    'Heading3',
    'Heart',
    'Highlighter',
    'Image',
    'ImagePlus',
    'Inbox',
    'Info',
    'Italic',
    'KeyRound',
    'Landmark',
    'Layers',
    'LayoutGrid',
    'LayoutList',
    'Lightbulb',
    'Link',
    'List',
    'ListChecks',
    'ListOrdered',
    'Lock',
    'Map',
    'Megaphone',
    'Menu',
    'MessageSquare',
    'MessagesSquare',
    'Minus',
    'Network',
    'Notebook',
    'Palette',
    'PanelBottom',
    'PanelLeft',
    'PanelRight',
    'Pen',
    'Pencil',
    'PenTool',
    'Pin',
    'PinOff',
    'Play',
    'Plus',
    'Power',
    'PowerOff',
    'Redo2',
    'RefreshCw',
    'Regex',
    'Repeat',
    'Replace',
    'Reply',
    'RotateCcw',
    'Scissors',
    'Search',
    'Send',
    'SeparatorHorizontal',
    'Server',
    'Settings',
    'Settings2',
    'Share',
    'Share2',
    'Sigma',
    'Smile',
    'Sparkles',
    'Square',
    'SquareCheck',
    'SquareKanban',
    'SquarePlus',
    'SquareSlash',
    'SquareTerminal',
    'SquareX',
    'Star',
    'Table',
    'Tag',
    'TextQuote',
    'Trash2',
    'TriangleAlert',
    'Undo2',
    'Ungroup',
    'Users',
    'Vote',
    'WholeWord',
    'Wrench',
    'X',
    'Zap',
    'ZoomIn',
    'ZoomOut',
]
