// app/src/icons/lucideAliases.ts
//
// Lucide icon name -> Phosphor slug, for vaults imported from Obsidian. Its Iconize plugin writes
// `icon: LiHouse` / `icon: LiMountain` into note frontmatter — Lucide names behind an `Li` prefix.
// registry-core already strips the prefix and matches case/separator-insensitively, so every Lucide
// name that Phosphor spells the same way (`LiHouse` -> house, `LiLeaf` -> leaf, `LiSignPost` ->
// signpost) resolves against the full icon library with no entry here.
//
// This table is ONLY the names the two sets spell differently. Values are Phosphor slugs from the
// full library (icon-library.json), never art — registry.ts resolves them there, and
// registry-library.test.ts checks every one resolves, so a typo fails a test instead of drawing
// the dashed "?" fallback. Keys are Lucide's PascalCase names WITHOUT the prefix.
export const LUCIDE_ALIASES: Record<string, string> = {
    Mountain: 'mountains',
    MountainSnow: 'mountains',
    Home: 'house',
    Dice1: 'dice-one',
    Dice2: 'dice-two',
    Dice3: 'dice-three',
    Dice4: 'dice-four',
    Dice5: 'dice-five',
    Dice6: 'dice-six',
    Dices: 'dice-five',
    IdCard: 'identification-card',
    Languages: 'translate',
    CarFront: 'car',
    RectangleVertical: 'rectangle',
    RectangleHorizontal: 'rectangle',
    Grid2x2: 'grid-four',
    Grid3x2: 'grid-four',
    Fence: 'wall',
    Mail: 'envelope',
    Music: 'music-note',
    Film: 'film-strip',
    Utensils: 'fork-knife',
    UtensilsCrossed: 'fork-knife',
    Plane: 'airplane',
    Dumbbell: 'barbell',
    DollarSign: 'currency-dollar',
    Trees: 'tree',
    TreePine: 'tree-evergreen',
    Library: 'books',
    LibraryBig: 'books',
    School: 'graduation-cap',
    Building: 'buildings',
    Building2: 'buildings',
    Store: 'storefront',
    Settings: 'gear',
    Search: 'magnifying-glass',
    Trash: 'trash',
    Trash2: 'trash',
    MapPin: 'map-pin',
    Map: 'map-trifold',
    Mic: 'microphone',
    Sprout: 'plant',
    Flower2: 'flower',
    Pill: 'pill',
    Stethoscope: 'stethoscope',
    Activity: 'heartbeat',
    Bike: 'bicycle',
    Ship: 'boat',
    TrainFront: 'train',
    Gamepad2: 'game-controller',
    Gamepad: 'game-controller',
    PawPrint: 'paw-print',
    CircleUser: 'user-circle',
    User: 'user',
    MessageCircle: 'chat-circle',
    PiggyBank: 'piggy-bank',
    Landmark: 'bank',
    BookMarked: 'book-bookmark',
    NotebookPen: 'notebook',
    Brush: 'paint-brush',
    Paintbrush: 'paint-brush',
    Shirt: 't-shirt',
    FlaskConical: 'flask',
    Sun: 'sun',
    CloudRain: 'cloud-rain',
    Laptop: 'laptop',
    Smartphone: 'device-mobile',
    Tv: 'television',
}
