// app/src/icons/registry-pixel.test.ts
//
// Guards the pixel half of the icon registry (pixelPaths.ts, generated by
// app/scripts/build-pixel-icons.ts) and the glyph/pixel split in registry.ts.
import { test, expect } from "bun:test";
import { resolveIcon, allIcons, type IconArt } from "./registry";
import { PIXEL_PATHS } from "./pixelPaths";

/** The seven surface glyphs — these must NEVER become pixel art (design/ascii/README.md). */
const SURFACES: [string, string][] = [
  ["Share2", "⁘"],
  ["FileText", "✎"],
  ["Table", "▤"],
  ["Calendar", "▦"],
  ["MessageSquare", "◈"],
  ["Bot", "✳"],
  ["Folder", "▸"],
];

test("the seven surface glyphs stay typed characters", () => {
  for (const [name, glyph] of SURFACES) {
    expect(resolveIcon(name)).toEqual({ kind: "glyph", text: glyph });
  }
});

test("utility names resolve to pixel art", () => {
  for (const name of ["Plus", "Search", "Trash2", "ChevronDown", "Settings", "Star"]) {
    expect(resolveIcon(name)?.kind).toBe("pixel");
  }
});

test("names whose ASCII form is the drawing stay typed", () => {
  expect(resolveIcon("X")).toEqual({ kind: "glyph", text: "x" });
  expect(resolveIcon("Square")).toEqual({ kind: "glyph", text: "[ ]" });
  expect(resolveIcon("SquareCheck")).toEqual({ kind: "glyph", text: "[x]" });
  expect(resolveIcon("Regex")).toEqual({ kind: "glyph", text: ".*" });
});

test("every pixel path is well-formed 24x24 path data", () => {
  for (const [name, d] of Object.entries(PIXEL_PATHS)) {
    // Absolute moveto first: a leading relative `m` would be mispositioned when the generator
    // concatenates several shapes into one path.
    expect(`${name}: ${d.slice(0, 1)}`).toBe(`${name}: M`);
    // Only path commands the flattener emits, and no coordinate outside the grid.
    expect(`${name}: ${/^[MLHVZmlhvz0-9,.\s-]+$/.test(d)}`).toBe(`${name}: true`);
    for (const n of d.match(/-?\d+(\.\d+)?/g) ?? []) {
      expect(`${name}: ${Math.abs(Number(n)) <= 24}`).toBe(`${name}: true`);
    }
  }
});

test("resolution is case/separator-insensitive for pixel icons too", () => {
  const plus = resolveIcon("Plus") as IconArt;
  expect(resolveIcon("plus")).toEqual(plus);
  expect(resolveIcon("PlusIcon")).toEqual(plus);
  expect(resolveIcon("LiPlus")).toEqual(plus);
});

test("allIcons covers both kinds and every name is unique", () => {
  const all = allIcons();
  const kinds = new Set(all.map((e) => e.Component.kind));
  expect(kinds).toEqual(new Set(["glyph", "pixel"]));
  expect(new Set(all.map((e) => e.name)).size).toBe(all.length);
  // The picker shows the whole set; a regression that dropped the pixel map would still pass
  // the surface assertions above, so assert the bulk is there.
  expect(all.filter((e) => e.Component.kind === "pixel").length).toBeGreaterThan(100);
});
