import { test, expect } from 'bun:test'
import { createServer } from '../server'
import { makeSampleVault } from '../../test/helpers'

// The set of `METHOD /path` keys createServer serves, sorted. A route moved between modules must
// not appear, vanish or change method; edit this list only when a route is deliberately added or removed.
const EXPECTED = [
    'GET /abs-path',
    'GET /agents/free',
    'GET /asset',
    'GET /base',
    'GET /bismuth/install',
    'GET /cards/all',
    'GET /cards/decks',
    'GET /cards/due',
    'GET /cards/note',
    'GET /chat/session-messages',
    'GET /chat/sessions',
    'GET /config',
    'GET /daemon/devices',
    'GET /daemon/install',
    'GET /daemon/logs',
    'GET /daemon/pages',
    'GET /daemon/snapshot',
    'GET /daemon/status',
    'GET /doctor',
    'GET /events',
    'GET /file',
    'GET /gcal/callback',
    'GET /gcal/status',
    'GET /graph',
    'GET /graph/views',
    'GET /meta',
    'GET /opencode/providers',
    'GET /relay/snapshot',
    'GET /schema',
    'GET /settings',
    'GET /status-bar',
    'GET /tasks',
    'GET /tasks/migration',
    'GET /templates',
    'GET /terminal/info',
    'GET /themes',
    'GET /tree',
    'GET /ui/windows',
    'GET /update/progress',
    'GET /update/status',
    'GET /vault-data',
    'GET /version',
    'POST /agents/free/install',
    'POST /asset',
    'POST /asset/fetch',
    'POST /backup',
    'POST /bismuth/install',
    'POST /cards/review',
    'POST /chat/search',
    'POST /convert/heic',
    'POST /create',
    'POST /daemon/cron/delete',
    'POST /daemon/cron/run',
    'POST /daemon/cron/toggle',
    'POST /daemon/owner',
    'POST /daemon/pages',
    'POST /daemon/pages/archive',
    'POST /daemon/pages/mark-failed',
    'POST /daemon/pages/resolve',
    'POST /daemon/process/delete',
    'POST /daemon/process/toggle',
    'POST /daemon/setup',
    'POST /daemon/update',
    'POST /daily-note',
    'POST /delete',
    'POST /delete-property',
    'POST /doctor/fix',
    'POST /folder-icon',
    'POST /folder-visibility',
    'POST /gcal/auth/start',
    'POST /gcal/credentials',
    'POST /gcal/disconnect',
    'POST /gcal/sync',
    'POST /list-dir',
    'POST /move',
    'POST /open-folder',
    'POST /opencode/auth',
    'POST /opencode/oauth/authorize',
    'POST /opencode/oauth/callback',
    'POST /relay/session',
    'POST /relay/session/end',
    'POST /relay/subagent/start',
    'POST /relay/subagent/stop',
    'POST /replace',
    'POST /restore',
    'POST /row/delete',
    'POST /row/reorder',
    'POST /row/update',
    'POST /rows',
    'POST /rows/update',
    'POST /search',
    'POST /search-prompt',
    'POST /set-properties',
    'POST /set-property',
    'POST /set-setting',
    'POST /status-bar/trust',
    'POST /tasks/archive',
    'POST /tasks/create',
    'POST /tasks/delete',
    'POST /tasks/move',
    'POST /tasks/reschedule',
    'POST /tasks/toggle',
    'POST /tasks/update',
    'POST /tmp-file',
    'POST /ui/command',
    'POST /update/apply',
    'PUT /file',
]

test('createServer serves exactly the expected route keys', async () => {
    const { vault, memory } = await makeSampleVault()
    const server = createServer({ vault, memory, port: 0 })
    try {
        const keys = [
            ...(server as unknown as { routeKeys: string[] }).routeKeys,
        ].sort()
        expect(keys).toEqual(EXPECTED)
    } finally {
        await server.stop(true)
    }
})
