use std::sync::Mutex;
use tauri::Manager;
use tauri_plugin_shell::process::CommandChild;
use tauri_plugin_shell::ShellExt;

// Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

// Handle to the spawned core server, killed when the app exits so we never orphan it.
struct Backend(Mutex<Option<CommandChild>>);

// The vault + memory dirs the backend serves. Persisted in the app config dir so a
// Finder-launched app (which has no shell env) remembers the user's choice. First run
// (or a stale/missing vault) prompts a native folder picker.
#[derive(serde::Serialize, serde::Deserialize, Default)]
struct AppConfig {
    vault: String,
    memory: String,
}

fn config_path(app: &tauri::AppHandle) -> Option<std::path::PathBuf> {
    let dir = app.path().app_config_dir().ok()?;
    Some(dir.join("config.json"))
}

fn read_config(app: &tauri::AppHandle) -> Option<AppConfig> {
    let text = std::fs::read_to_string(config_path(app)?).ok()?;
    serde_json::from_str(&text).ok()
}

fn write_config(app: &tauri::AppHandle, cfg: &AppConfig) {
    let Some(path) = config_path(app) else { return };
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    if let Ok(text) = serde_json::to_string_pretty(cfg) {
        let _ = std::fs::write(path, text);
    }
}

fn default_memory_dir() -> String {
    let home = std::env::var("HOME").unwrap_or_default();
    format!("{home}/.claude-bot/memory")
}

// Resolve vault + memory: a valid saved config wins; otherwise prompt a folder picker
// for the vault (memory defaults to ~/.claude-bot/memory) and persist. Returns None if
// the user cancels the picker — the app still opens, just with no backend.
fn resolve_vault_memory(app: &tauri::AppHandle) -> Option<(String, String)> {
    if let Some(cfg) = read_config(app) {
        if !cfg.vault.is_empty() && std::path::Path::new(&cfg.vault).is_dir() {
            let memory = if cfg.memory.is_empty() { default_memory_dir() } else { cfg.memory };
            return Some((cfg.vault, memory));
        }
    }
    use tauri_plugin_dialog::DialogExt;
    let picked = app
        .dialog()
        .file()
        .set_title("Choose your Bismuth vault folder")
        .blocking_pick_folder()
        .and_then(|fp| fp.into_path().ok())?;
    let vault = picked.to_string_lossy().to_string();
    let memory = default_memory_dir();
    let _ = std::fs::create_dir_all(&memory);
    write_config(app, &AppConfig { vault: vault.clone(), memory: memory.clone() });
    Some((vault, memory))
}

// Find a free TCP port by binding :0 and reading the assigned port.
fn pick_free_port() -> u16 {
    std::net::TcpListener::bind("127.0.0.1:0")
        .ok()
        .and_then(|l| l.local_addr().ok())
        .map(|a| a.port())
        .unwrap_or(4321)
}

// Spawn the bundled `bismuth-core` sidecar on a free port. Returns the port on success
// so the caller can point the webview at it (via window.__OA_API__). Stores the child so
// it's killed on exit. Best-effort: returns None if no vault was chosen or the spawn
// fails (the app still opens, against the frontend's default :4321 / "disconnected").
fn start_backend(app: &tauri::AppHandle) -> Option<u16> {
    let (vault, memory) = resolve_vault_memory(app)?;
    let port = pick_free_port();
    let sidecar = match app.shell().sidecar("bismuth-core") {
        Ok(c) => c,
        Err(e) => { eprintln!("bismuth: sidecar resolve failed: {e}"); return None; }
    };
    let cmd = sidecar.args(["--vault", &vault, "--memory", &memory, "--port", &port.to_string()]);
    match cmd.spawn() {
        Ok((mut rx, child)) => {
            app.state::<Backend>().0.lock().unwrap().replace(child);
            // Drain the event stream so its buffer never blocks the child's IO.
            tauri::async_runtime::spawn(async move { while rx.recv().await.is_some() {} });
            eprintln!("bismuth: core sidecar started (vault={vault}, :{port})");
            Some(port)
        }
        Err(e) => { eprintln!("bismuth: failed to spawn core sidecar: {e}"); None }
    }
}

// Build the main window. `injected` (Some when we spawned a backend on a known port)
// is set as `window.__OA_API__` before any app JS runs, so the frontend talks to our
// spawned core. In dev (no spawn) it's None → the frontend uses its :4321 default
// (the concurrently-launched dev backend).
fn build_main_window(app: &tauri::AppHandle, injected: Option<String>) -> tauri::Result<()> {
    let mut builder = tauri::WebviewWindowBuilder::new(app, "main", tauri::WebviewUrl::default())
        .title("app")
        .inner_size(1200.0, 800.0);
    if let Some(api) = injected {
        builder = builder.initialization_script(&format!("window.__OA_API__={api:?};"));
    }
    builder.build()?;
    Ok(())
}

// Pre-rendered dock-icon PNGs, one per Bismuth mark (generated by
// app/scripts/gen-dock-icons.ts from app/public/logos/*.svg). Embedded so they're
// available in both dev and bundled builds without any filesystem lookup.
#[cfg(target_os = "macos")]
fn mark_png(name: &str) -> Option<&'static [u8]> {
    Some(match name {
        "hopper-crystal" => include_bytes!("../icons/marks/hopper-crystal.png"),
        "node-b" => include_bytes!("../icons/marks/node-b.png"),
        "square-funnel" => include_bytes!("../icons/marks/square-funnel.png"),
        "nested-diamonds" => include_bytes!("../icons/marks/nested-diamonds.png"),
        "pinwheel" => include_bytes!("../icons/marks/pinwheel.png"),
        "node-crystal" => include_bytes!("../icons/marks/node-crystal.png"),
        "lattice" => include_bytes!("../icons/marks/lattice.png"),
        "diamond-bloom" => include_bytes!("../icons/marks/diamond-bloom.png"),
        "node-diamond" => include_bytes!("../icons/marks/node-diamond.png"),
        "octagon-bloom" => include_bytes!("../icons/marks/octagon-bloom.png"),
        "spin-cross" => include_bytes!("../icons/marks/spin-cross.png"),
        "tri-bloom" => include_bytes!("../icons/marks/tri-bloom.png"),
        "radial-graph" => include_bytes!("../icons/marks/radial-graph.png"),
        "node-rings" => include_bytes!("../icons/marks/node-rings.png"),
        _ => return None,
    })
}

// Read `appearance.icon` from the vault's settings.yaml (OA_VAULT). Returns None
// if unset/absent. Tiny scoped scan rather than a YAML dependency: the `icon:` key
// inside the top-level `appearance:` block.
#[cfg(target_os = "macos")]
fn vault_icon_name() -> Option<String> {
    let vault = std::env::var("OA_VAULT").ok()?;
    let text = std::fs::read_to_string(std::path::Path::new(&vault).join("settings.yaml")).ok()?;
    let mut in_appearance = false;
    for line in text.lines() {
        let is_top_level = !line.is_empty() && !line.starts_with(char::is_whitespace);
        if is_top_level {
            in_appearance = line.trim_start().starts_with("appearance:");
            continue;
        }
        if in_appearance {
            if let Some(rest) = line.trim().strip_prefix("icon:") {
                return Some(rest.trim().trim_matches(|c| c == '"' || c == '\'').to_string());
            }
        }
    }
    None
}

// Set the macOS dock icon to the vault's chosen mark. Runs at the `Ready` event
// (pre-composite), mirroring Tauri's own internal dev call.
#[cfg(target_os = "macos")]
fn apply_vault_dock_icon() {
    use objc2::{AllocAnyThread, MainThreadMarker};
    use objc2_app_kit::{NSApplication, NSImage};
    use objc2_foundation::NSData;
    let Some(png) = vault_icon_name().and_then(|n| mark_png(&n)) else {
        return;
    };
    let Some(mtm) = MainThreadMarker::new() else {
        return;
    };
    let data = NSData::with_bytes(png);
    if let Some(image) = NSImage::initWithData(NSImage::alloc(), &data) {
        let nsapp = NSApplication::sharedApplication(mtm);
        unsafe { nsapp.setApplicationIconImage(Some(&image)) };
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let app = tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_shell::init())
        .manage(Backend(Mutex::new(None)))
        .invoke_handler(tauri::generate_handler![greet])
        .setup(|app| {
            // Bundled builds spawn their own core server on a free port; in dev
            // (`bun run dev`) the concurrently-launched core already owns :4321, so
            // don't double-spawn. The window is created here (not in tauri.conf.json)
            // so the spawned port can be injected before any app JS runs.
            let injected = if !cfg!(debug_assertions) {
                start_backend(&app.handle()).map(|p| format!("http://localhost:{p}"))
            } else {
                None
            };
            build_main_window(&app.handle(), injected)?;
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application");

    app.run(|app_handle, event| {
        #[cfg(target_os = "macos")]
        if let tauri::RunEvent::Ready = event {
            apply_vault_dock_icon();
        }
        // Kill the spawned core server when the app quits — no orphaned backend.
        if let tauri::RunEvent::Exit = event {
            if let Some(child) = app_handle.state::<Backend>().0.lock().unwrap().take() {
                let _ = child.kill();
            }
        }
    });
}
