// Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

// Pre-rendered dock-icon PNGs, one per Bismuth mark (generated by
// app/scripts/gen-dock-icons.ts from app/public/logos/*.svg). Embedded so they're
// available in both dev and bundled builds without any filesystem lookup.
#[cfg(target_os = "macos")]
fn mark_png(name: &str) -> Option<&'static [u8]> {
    Some(match name {
        "hopper-crystal" => include_bytes!("../icons/marks/hopper-crystal.png"),
        "node-b" => include_bytes!("../icons/marks/node-b.png"),
        "square-funnel" => include_bytes!("../icons/marks/square-funnel.png"),
        "nested-diamonds" => include_bytes!("../icons/marks/nested-diamonds.png"),
        "pinwheel" => include_bytes!("../icons/marks/pinwheel.png"),
        "node-crystal" => include_bytes!("../icons/marks/node-crystal.png"),
        "lattice" => include_bytes!("../icons/marks/lattice.png"),
        "diamond-bloom" => include_bytes!("../icons/marks/diamond-bloom.png"),
        "node-diamond" => include_bytes!("../icons/marks/node-diamond.png"),
        "octagon-bloom" => include_bytes!("../icons/marks/octagon-bloom.png"),
        "spin-cross" => include_bytes!("../icons/marks/spin-cross.png"),
        "tri-bloom" => include_bytes!("../icons/marks/tri-bloom.png"),
        "radial-graph" => include_bytes!("../icons/marks/radial-graph.png"),
        "node-rings" => include_bytes!("../icons/marks/node-rings.png"),
        _ => return None,
    })
}

// Read `appearance.icon` from the vault's settings.yaml (OA_VAULT). Returns None
// if unset/absent. Tiny scoped scan rather than a YAML dependency: the `icon:` key
// inside the top-level `appearance:` block.
#[cfg(target_os = "macos")]
fn vault_icon_name() -> Option<String> {
    let vault = std::env::var("OA_VAULT").ok()?;
    let text = std::fs::read_to_string(std::path::Path::new(&vault).join("settings.yaml")).ok()?;
    let mut in_appearance = false;
    for line in text.lines() {
        let is_top_level = !line.is_empty() && !line.starts_with(char::is_whitespace);
        if is_top_level {
            in_appearance = line.trim_start().starts_with("appearance:");
            continue;
        }
        if in_appearance {
            if let Some(rest) = line.trim().strip_prefix("icon:") {
                return Some(rest.trim().trim_matches(|c| c == '"' || c == '\'').to_string());
            }
        }
    }
    None
}

// Set the macOS dock icon to the vault's chosen mark. Runs at the `Ready` event
// (pre-composite), mirroring Tauri's own internal dev call.
#[cfg(target_os = "macos")]
fn apply_vault_dock_icon() {
    use objc2::{AllocAnyThread, MainThreadMarker};
    use objc2_app_kit::{NSApplication, NSImage};
    use objc2_foundation::NSData;
    let Some(png) = vault_icon_name().and_then(|n| mark_png(&n)) else {
        return;
    };
    let Some(mtm) = MainThreadMarker::new() else {
        return;
    };
    let data = NSData::with_bytes(png);
    if let Some(image) = NSImage::initWithData(NSImage::alloc(), &data) {
        let nsapp = NSApplication::sharedApplication(mtm);
        unsafe { nsapp.setApplicationIconImage(Some(&image)) };
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let app = tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![greet])
        .build(tauri::generate_context!())
        .expect("error while building tauri application");

    app.run(|_app_handle, _event| {
        #[cfg(target_os = "macos")]
        if let tauri::RunEvent::Ready = _event {
            apply_vault_dock_icon();
        }
    });
}
