// core/src/agentBackends/codexHooks.ts
//
// Generates a project-scoped `.codex/hooks.json` (+ its companion reporting script) so a bare
// `codex` launched with cwd = a Bismuth vault reports its session lifecycle into Bismuth's
// "agents" graph — WITHOUT a PATH shim. Codex auto-discovers `.codex/hooks.json` for any `codex`
// invocation whose cwd is inside that project (alongside the global `~/.codex/hooks.json`); see
// docs/chat/backends.md's Surface 3 section and this task's research report. MEDIUM confidence: the
// project-scope file-discovery mechanics came from a source read of codex-rs/hooks (not a stable
// dated docs page) — the hooks/`[hooks]` config.toml mechanism itself IS on Codex's current
// published docs, so the feature is real; only the exact discovery path is unverified against an
// installed CLI. If wrong, the failure mode is simply "no agents-graph nodes for Codex sessions" —
// never a crash, never a wrong node (see writeCodexHookScript's gating).
//
// Correlation without a PATH shim: core/src/terminal.ts's buildPtyEnv injects CLAUDE_TERMINAL_ID +
// CLAUDE_RELAY_URL into EVERY terminal tab's env, regardless of which binary the tab runs (verified
// by reading terminal.ts — this task does not edit it). So a Codex hook command inherits both vars
// exactly like the Claude relay's hooks do, and the generated script below reads them the same way
// relay/lib/report.ts does.
//
// Both files are written directly INTO THE VAULT (not resolved from a Bismuth-bundled resource
// dir), so this works identically in dev and the packaged app with zero Tauri-bundling changes —
// the generator just writes two plain text files, mirroring agentBackends/agentsMd.ts's approach.
//
// Opt-in (settings.codex.installRelayHooks, default false, read via core/src/settings.ts's
// readCodexOptIns) — writing into a user's vault uninvited is not something Bismuth does, same rule
// as AGENTS.md.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const CODEX_HOOK_SCRIPT_NAME = "bismuth-relay-hook.ts";
const CODEX_DIR_NAME = ".codex";
const HOOKS_FILE_NAME = "hooks.json";

const HOOKS_JSON_DESCRIPTION = "Bismuth relay lifecycle hooks — reports this Codex session to the in-app agents graph.";

/**
 * The reporting script's full source, written verbatim to `<vault>/.codex/bismuth-relay-hook.ts`.
 * Mirrors relay/lib/report.ts's discipline exactly: gated on CLAUDE_TERMINAL_ID (no-ops entirely
 * outside a Bismuth terminal tab), a tight fetch timeout, every error swallowed, and the process
 * ALWAYS exits 0 — a hook must never fail or block the user's Codex session.
 *
 * Field names read off stdin (session_id, cwd, agent_id, agent_type, last_assistant_message) match
 * Codex's SessionStart/SubagentStart/SubagentStop/SessionEnd hook payloads verbatim per the research
 * report backing this task — the same snake_case shape Claude Code's own hooks use, so one script
 * covers both event families without per-field translation. Plain JS (no TypeScript-only syntax) so
 * it runs unmodified under `bun run` with no transpile-time surprises.
 */
export function codexHookScriptSource(): string {
  return [
    "#!/usr/bin/env bun",
    "// Auto-generated by Bismuth (core/src/agentBackends/codexHooks.ts) — regenerated whenever",
    "// settings.codex.installRelayHooks is on; DO NOT EDIT (edits are overwritten on the next regen).",
    "//",
    "// Reports this Codex session's lifecycle to Bismuth's in-app \"agents\" graph via POST /relay/*.",
    "// Every error is swallowed and the process always exits 0 — a hook must never block or fail the",
    "// user's Codex session. No-ops entirely outside a Bismuth terminal tab (CLAUDE_TERMINAL_ID unset).",
    "const EVENT = process.argv[2] || \"\";",
    "const TERMINAL_ID = process.env.CLAUDE_TERMINAL_ID;",
    "const BUDGET_MS = 2000;",
    "",
    "function relayBase() {",
    "  let base = process.env.CLAUDE_RELAY_URL || \"http://localhost:4321\";",
    "  while (base.length > 0 && base.charAt(base.length - 1) === \"/\") base = base.slice(0, -1);",
    "  return base;",
    "}",
    "",
    "async function post(path, body) {",
    "  try {",
    "    await fetch(relayBase() + path, {",
    "      method: \"POST\",",
    "      headers: { \"content-type\": \"application/json\" },",
    "      body: JSON.stringify(body),",
    "      signal: AbortSignal.timeout(BUDGET_MS),",
    "    });",
    "  } catch {",
    "    // relay unreachable/slow — never block the session.",
    "  }",
    "}",
    "",
    "async function readStdin() {",
    "  try {",
    "    const text = await new Response(Bun.stdin.stream()).text();",
    "    return text ? JSON.parse(text) : {};",
    "  } catch {",
    "    return {};",
    "  }",
    "}",
    "",
    "function str(v) {",
    "  return typeof v === \"string\" && v ? v : undefined;",
    "}",
    "",
    "async function main() {",
    "  if (!TERMINAL_ID) return; // not launched from a Bismuth terminal tab",
    "  const input = await readStdin();",
    "",
    "  if (EVENT === \"session-start\") {",
    "    const sessionId = str(input.session_id);",
    "    if (!sessionId) return;",
    "    await post(\"/relay/session\", { sessionId, terminalId: TERMINAL_ID, cwd: str(input.cwd) || \"\", backend: \"codex\" });",
    "  } else if (EVENT === \"subagent-start\") {",
    "    const parentSessionId = str(input.session_id);",
    "    const agentId = str(input.agent_id);",
    "    if (!parentSessionId || !agentId) return;",
    "    await post(\"/relay/subagent/start\", { parentSessionId, agentId, agentType: str(input.agent_type) || \"agent\" });",
    "  } else if (EVENT === \"subagent-stop\") {",
    "    const agentId = str(input.agent_id);",
    "    if (!agentId) return;",
    "    await post(\"/relay/subagent/stop\", { agentId, lastMessage: str(input.last_assistant_message) });",
    "  } else if (EVENT === \"session-end\") {",
    "    const sessionId = str(input.session_id);",
    "    if (!sessionId) return;",
    "    await post(\"/relay/session/end\", { sessionId });",
    "  }",
    "}",
    "",
    "main()",
    "  .catch(() => {})",
    "  .finally(() => process.exit(0));",
    "",
  ].join("\n");
}

interface CodexHookCommand {
  type: "command";
  command: string;
  timeout_sec: number;
}
interface CodexHookMatcher {
  matcher?: string;
  hooks: CodexHookCommand[];
}
export interface CodexHooksJson {
  description: string;
  hooks: Record<string, CodexHookMatcher[]>;
}

function commandFor(scriptPath: string, event: string): string {
  // JSON.stringify quotes+escapes the path for embedding in a shell-parsed command string — safe
  // for ordinary filesystem paths (spaces included); a path containing `$`/backticks is out of
  // scope (same limitation every other generated shell command in this codebase accepts).
  return `bun run ${JSON.stringify(scriptPath)} ${event}`;
}

/** The hooks.json content Bismuth wants: SessionStart/SubagentStart/SubagentStop/SessionEnd, each
 *  invoking `scriptPath` (the absolute path to codexHookScriptSource()'s written-out file) with the
 *  event name as its one argv. `SessionStart`'s matcher covers every source Codex documents
 *  (startup/resume/clear/compact) so a resumed or `codex exec resume` session re-registers too,
 *  mirroring the Claude relay's SessionStart hook. */
export function buildCodexHooksJson(scriptPath: string): CodexHooksJson {
  return {
    description: HOOKS_JSON_DESCRIPTION,
    hooks: {
      SessionStart: [{ matcher: "startup|resume|clear|compact", hooks: [{ type: "command", command: commandFor(scriptPath, "session-start"), timeout_sec: 3 }] }],
      SubagentStart: [{ hooks: [{ type: "command", command: commandFor(scriptPath, "subagent-start"), timeout_sec: 3 }] }],
      SubagentStop: [{ hooks: [{ type: "command", command: commandFor(scriptPath, "subagent-stop"), timeout_sec: 3 }] }],
      SessionEnd: [{ hooks: [{ type: "command", command: commandFor(scriptPath, "session-end"), timeout_sec: 3 }] }],
    },
  };
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/** True when a hooks.json matcher ENTRY is one Bismuth authored — matched by its command string
 *  referencing our script's basename, so a regen can find-and-replace its OWN prior entries without
 *  touching anything else (a user's own PreToolUse/PermissionRequest hooks, another tool's entries
 *  for the SAME event names, etc). */
function isOurHookEntry(entry: unknown): boolean {
  if (!isRecord(entry) || !Array.isArray(entry.hooks)) return false;
  return entry.hooks.some(
    (h) => isRecord(h) && typeof h.command === "string" && h.command.includes(CODEX_HOOK_SCRIPT_NAME),
  );
}

/**
 * Structure-preserving upsert of Bismuth's four hook events into an existing (or absent)
 * `.codex/hooks.json`. PURE. Preserves every unrelated top-level key, every OTHER event's matcher
 * list, and any of the user's own entries under OUR four event names (only entries this module
 * itself authored, per isOurHookEntry, are replaced — never appended a second time on a regen, and
 * never removing something Bismuth didn't write). A file that isn't valid JSON, or whose top level
 * isn't a plain object, is left completely untouched (returned verbatim) rather than risking
 * clobbering something Bismuth can't parse.
 */
export function upsertCodexHooksJson(existingText: string | null, scriptPath: string): { text: string; warning?: string } {
  let parsed: Record<string, unknown>;
  if (existingText == null) {
    parsed = {};
  } else {
    try {
      const v: unknown = JSON.parse(existingText);
      if (!isRecord(v)) return { text: existingText, warning: "existing .codex/hooks.json isn't a JSON object — left untouched" };
      parsed = v;
    } catch {
      return { text: existingText, warning: "existing .codex/hooks.json isn't valid JSON — left untouched" };
    }
  }

  const hooks: Record<string, unknown> = isRecord(parsed.hooks) ? { ...parsed.hooks } : {};
  const ours = buildCodexHooksJson(scriptPath).hooks;
  for (const [event, entries] of Object.entries(ours)) {
    const existingArr = Array.isArray(hooks[event]) ? (hooks[event] as unknown[]) : [];
    const keepOthers = existingArr.filter((e) => !isOurHookEntry(e));
    hooks[event] = [...keepOthers, ...entries];
  }

  const next: Record<string, unknown> = { ...parsed, hooks };
  if (!("description" in next) || typeof next.description !== "string" || !next.description) {
    next.description = HOOKS_JSON_DESCRIPTION;
  }
  return { text: `${JSON.stringify(next, null, 2)}\n` };
}

/**
 * Best-effort: write `<vaultRoot>/.codex/bismuth-relay-hook.ts` and merge Bismuth's four hooks into
 * `<vaultRoot>/.codex/hooks.json`. Never throws — a filesystem hiccup here must not fail whatever
 * chat turn/session-open triggered it. Returns whether both writes succeeded.
 */
export function writeCodexHooksFiles(vaultRoot: string): boolean {
  try {
    const codexDir = join(vaultRoot, CODEX_DIR_NAME);
    mkdirSync(codexDir, { recursive: true });
    const scriptPath = join(codexDir, CODEX_HOOK_SCRIPT_NAME);
    writeFileSync(scriptPath, codexHookScriptSource());

    const hooksPath = join(codexDir, HOOKS_FILE_NAME);
    const existing = existsSync(hooksPath) ? readFileSync(hooksPath, "utf8") : null;
    const { text } = upsertCodexHooksJson(existing, scriptPath);
    writeFileSync(hooksPath, text);
    return true;
  } catch {
    return false;
  }
}
